# Install Nginx
- name: "apt-get update"
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Install Nginx
  apt:
    name: nginx
    state: present
  when: ansible_facts['os_family'] == 'Debian'
- name: generate Nginx site config
  template:
     src: site.conf.j2
     dest: /etc/nginx/sites-available/site.conf
     owner: root
     group: root
     mode: 0755
- name: Generate index.html
  template:
     src: index.html.j2
     dest: /var/www/html/index.html
     owner: root
     group: root
     mode: 0744
- name: Enable Nginx service
  systemd:
    name: nginx
    daemon_reload: yes
    enabled: yes
    state: started

